name: Build images

on:
  push:
    branches:
      - main
    paths:
      - apps/api/**
      - apps/playwright-service-ts/**
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build firecrawl image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/api
          push: true
          tags: ghcr.io/dbirks/firecrawl

      - name: Build playwright-service image
        uses: docker/build-push-action@v6
        with:
          context: ./apps/playwright-service-ts
          push: true
          tags: ghcr.io/dbirks/firecrawl-playwright
